server:
  port: 14082

spring:
  datasource:
    url: jdbc:mariadb://gb-sealcure-prd-rds.chje4j1rtvtm.ap-northeast-2.rds.amazonaws.com:3306/sealcure
    driver-class-name: org.mariadb.jdbc.Driver
    username: gbadmin
    password: wlqlthvmxm1!
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #DB?
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true #
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate:
      type:
        descriptor.sql: trace

dlInterface:
  auth_url: https://api.dlenc.co.kr/dgw20-30/oauth/create
  client_id: 854676b9e6abdcd6
  client_secret: d5c9de61656e226fc4a783bd50d74ec1b8a1c2138db2b7f2f41495101289439b
  transmit_url: https://api.dlenc.co.kr/dgw20-30/400067