server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://gb-sealcure-prd-rds.chje4j1rtvtm.ap-northeast-2.rds.amazonaws.com:3306/sealcure
    driver-class-name: org.mariadb.jdbc.Driver
    username: gbadmin
    password: wlqlthvmxm1!
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #DB?
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true #
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate:
      type:
        descriptor.sql: trace

envrioment:
  property: false