server:
  port: 14082

spring:
  datasource:
    url: jdbc:mariadb://gb-gblite-dev-rds.cww5ax3bcsku.ap-northeast-2.rds.amazonaws.com:3306/GBTEM
    driver-class-name: org.mariadb.jdbc.Driver
    username: gbadmin
    password: wlqlthvmxm1!
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #DB?
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        highlight_sql: true #
  h2:
    console:
      enabled: true

logging:
  level:
    root: warn
    org.hibernate:
      type:
        descriptor.sql: warn


# 추후 테스트로 변경 할 것 client_id, client_secret
dlInterface:
  auth_url: https://api.dlenc.co.kr/dgw20-30/oauth/create
  client_id: 7d44f21066a68985
  client_secret: ed5a2b0f83b37ea00cd977c8b5d8d5294ce33f08777bc76b9a4666e5d81ef191
  transmit_url: https://api.dlenc.co.kr/dgw20-30/400067